### ISSUE TITLE
Link to past months not working

### ISSUE THREAD

**Issue by bernd-bechermann** [dexterity42/SharedProjectTimesheetsBundle#14]
For me in shared view links to other months than the present one selected via the dropdown are missing the /public/ part in the url, so eg example.com/de/auth/shared-project-timesheets/1/* and not example.com/public/de/auth/shared-project-timesheets/1/*

Danke für das Plugin

**Comment by dexterity42** [comment]
The plugin uses the variable `app.request.pathinfo` that is exposed by symfony to define the url root. I'll have a look into it if there is a better solution to support subpath installations.

Please check if your issue is a result of a wrong webserver setup. The `public` folder of your kimai installation should be provided on root level `/`. Note that it can be dangerous to use the wrong document root. Did you use the Kimai "Webserver configuration" Guide to setup your webserver? See https://www.kimai.org/documentation/webserver-configuration.html

Thanks for your submission and for using the plugin 😃

**Comment by bernd-bechermann** [comment]
You were right. I seem to have forgotten to point the webserver to the public folder. Sorry for that. :) Works fine now. Danke!

**Comment by dexterity42** [comment]
You're welcome 👍🏻 closing this as your issue is fixed.
